spring.application.name=YalaDars
# Database
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wttxxnjbyxzoynsdjeim
spring.datasource.password=veryStrongPass12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
application.security.jwt.secret=809b9837-0d39-49cc-95d9-3f76e25047ed
application.security.jwt.expiration=86400000

# Server
server.port=8080