spring.application.name=YalaDars
spring.config.import=optional:classpath:application-local.properties
# Database
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wttxxnjbyxzoynsdjeim
spring.datasource.password=${DB_Password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# JPA
spring.jpa.hibernate.ddl-auto=validate   
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
application.security.jwt.secret=${JWT_Secret}
application.security.jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG


# Server
server.port=8080